// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeg9qNzD8z6jHJJVhWHg6_tC0ybJsfdPM',
    appId: '1:1060778350738:web:a9ac99d35408f322b02e4b',
    messagingSenderId: '1060778350738',
    projectId: 'chattingapp-a6cf2',
    authDomain: 'chattingapp-a6cf2.firebaseapp.com',
    storageBucket: 'chattingapp-a6cf2.appspot.com',
    measurementId: 'G-6CZ1YKC9XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMBKCvX5j3_ap9tkHrmI3kinzCsxHAlgM',
    appId: '1:1060778350738:android:62132d831e65134bb02e4b',
    messagingSenderId: '1060778350738',
    projectId: 'chattingapp-a6cf2',
    storageBucket: 'chattingapp-a6cf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaOX7cubRAvEnUph-9wxEYyKEc1jLOtHY',
    appId: '1:1060778350738:ios:04f08f9147e57ae8b02e4b',
    messagingSenderId: '1060778350738',
    projectId: 'chattingapp-a6cf2',
    storageBucket: 'chattingapp-a6cf2.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaOX7cubRAvEnUph-9wxEYyKEc1jLOtHY',
    appId: '1:1060778350738:ios:5874880c63fe8858b02e4b',
    messagingSenderId: '1060778350738',
    projectId: 'chattingapp-a6cf2',
    storageBucket: 'chattingapp-a6cf2.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
